#!/usr/bin/env bash

set -ueo pipefail

DOMAIN="$1"
DOMAIN_ALL="$*"

echo "$DOMAIN_ALL" |
  xargs printf -- '-d %s\n' |
  xargs letsencrypt certonly --webroot -w "/srv/www/default/"

mkdir -p "/srv/www/$DOMAIN/public"

cat > "/etc/nginx/sites-available/$DOMAIN" <<EOF
server {
        listen 443 ssl;
        listen [::]:443 ssl;
        charset UTF-8;

        ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
        # add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        server_name $DOMAIN_ALL;

        root /srv/www/$DOMAIN/public/;
}
EOF

ln -s "/etc/nginx/sites-available/$DOMAIN" "/etc/nginx/sites-enabled/"

service nginx reload
