#!/usr/bin/env bash

set -ueo pipefail

COMMAND="$1"
shift

case "$COMMAND" in
  cert)
    PRIMARY_DOMAIN="$1"
    DOMAINS="$*"
    if ! test -d "/etc/letsencrypt/live/$PRIMARY_DOMAIN"; then
      letsencrypt certonly --webroot -w "/srv/www/default/" $DOMAINS;
    fi
    ;;

  nginx)
    PRIMARY_DOMAIN="$1"
    NGINX_AVAILABLE="/etc/nginx/sites-available/$PRIMARY_DOMAIN"
    NGINX_ENABLED="/etc/nginx/sites-enabled/$PRIMARY_DOMAIN"

    cat > "$NGINX_AVAILABLE"
    if ! test -f "$NGINX_ENABLED";
      ln -s "$NGINX_AVAILABLE" "$NGINX_ENABLED";
    fi
    ;;
esac
